name: check
run-name: Lint and Type Check
on:
  push:
    branches:
      - dev
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Lint
        run: deno task lint
      - name: Type Check
        run: deno task check
