name: check
run-name: Lint and Type Check
on:
  push:
    branches:
      - dev
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Lint
        run: deno task lint
  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install vue-tsc
        run: npm i vue-tsc --no-save
      - name: Type Check
        run: deno task check
