name: check
run-name: Lint and Type Check
on:
  push:
    branches:
      - dev
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install Dependencies
        run: npm install
      - name: Lint and Check
        run: npm run check
